# fly.toml app configuration file generated for app-nameless-pine-7492 on 2024-10-10T07:35:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'app-nameless-pine-7492'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
